connect:
  host: <%= ENV.fetch('RABBITMQ_HOST', 'localhost') %>
  port: <%= ENV.fetch('RABBITMQ_PORT', '5672') %>
  username: <%= ENV.fetch('RABBITMQ_USER', 'guest') %>
  password: <%= ENV.fetch('RABBITMQ_PASSWORD', 'guest') %>

exchange:
  events:
    name: peatio.events
    type: direct
  finex-spot:
    name: finex.orderapi
    type: direct
  opendax:
    name: finex.orderapi
    type: direct

queue:
  deposit_collection_fees:
    name: peatio.deposit.collection_fees
  deposit_collection:
    name: peatio.deposit.collection
  deposit_coin_address:
    name: peatio.deposit.coin.address
    durable: true

binding:
  withdraw_coin:
    queue: withdraw_coin
  deposit_coin_address:
    queue: deposit_coin_address
  events_processor:
    queue: events_processor
    exchange: events

channel:
  trade_executor:
    prefetch: 5
  order_processor:
    prefetch: 5